sudo: */15: command not found
-bash: */15: No such file or directory
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
/bin/sh: 1: /home/ubuntu/Geo-Algo/.venv/bin/python: not found
16:20:03.159823
Trend lines re-computed and checked.
16:25:02.645260
Trend lines re-computed and checked.
16:30:02.903185
Trend lines re-computed and checked.
16:35:02.167809
Trend lines re-computed and checked.
09:00:04.565662
09:15:04.218207
09:30:03.858692
Trend lines re-computed and checked.
09:45:03.867068
Trend lines re-computed and checked.
10:00:03.754777
Trend lines re-computed and checked.
10:15:03.937713
Trend lines re-computed and checked.
10:30:03.839207
Trend lines re-computed and checked.
10:45:03.590064
Trend lines re-computed and checked.
11:00:03.464757
Trend lines re-computed and checked.
11:15:04.227882
Trend lines re-computed and checked.
11:30:04.069114
Trend lines re-computed and checked.
11:45:03.927902
Trend lines re-computed and checked.
12:00:03.740153
Trend lines re-computed and checked.
12:15:03.718113
Trend lines re-computed and checked.
12:30:03.552309
Trend lines re-computed and checked.
12:45:03.352546
Trend lines re-computed and checked.
13:00:04.168686
Trend lines re-computed and checked.
13:15:03.829611
Trend lines re-computed and checked.
13:30:03.621141
Trend lines re-computed and checked.
13:45:03.622162
Trend lines re-computed and checked.
14:00:03.590385
Trend lines re-computed and checked.
14:15:03.996933
Trend lines re-computed and checked.
14:30:03.987921
Trend lines re-computed and checked.
14:45:03.676262
Trend lines re-computed and checked.
15:00:03.441623
15:15:04.119528
15:30:03.834852
15:45:03.553375
09:00:04.606748
09:15:03.359586
09:30:04.095842
{'date': '2025-06-25', 'value': 1680.5} rec
1680.5 line_price
1840.0 1839.9 1840.0
1672.0975 1688.9025
True
[09:30] TrendLine 51 touched at 1680.5 (bar 2025-06-25 09:15:04–2025-06-25 09:30:04)
{'date': '2025-06-25', 'value': 1680.5} rec
1680.5 line_price
1840.3 1839.9 1840.0
1672.0975 1688.9025
True
[09:30] TrendLine 53 touched at 1680.5 (bar 2025-06-25 09:15:04–2025-06-25 09:30:04)
{'date': '2025-06-25', 'value': 1952.0739658493403} rec
1952.0739658493403 line_price
1840.3 1839.9 1840.0
1942.3135658493403 1961.8343658493403
True
[09:30] TrendLine 54 touched at 1952.0739658493403 (bar 2025-06-25 09:15:04–2025-06-25 09:30:04)
{'date': '2025-06-25', 'value': 1993.35} rec
1993.35 line_price
1975.9 1974.7 1974.9
1983.3832 2003.3168
True
[09:30] TrendLine 55 touched at 1993.35 (bar 2025-06-25 09:15:04–2025-06-25 09:30:04)
{'date': '2025-06-25', 'value': 2217.6937109190203} rec
2217.6937109190203 line_price
1975.9 1974.7 1974.9
2206.6052109190203 2228.7822109190203
True
[09:30] TrendLine 56 touched at 2217.6937109190203 (bar 2025-06-25 09:15:04–2025-06-25 09:30:04)
Trend lines re-computed and checked.
09:45:04.161505
Trend lines re-computed and checked.
10:00:03.967700
Trend lines re-computed and checked.
10:15:03.685681
Trend lines re-computed and checked.
10:30:03.469701
Trend lines re-computed and checked.
10:45:04.201125
Trend lines re-computed and checked.
11:00:03.987503
Trend lines re-computed and checked.
11:15:03.937494
Trend lines re-computed and checked.
11:30:03.701398
Trend lines re-computed and checked.
11:45:03.520866
Trend lines re-computed and checked.
12:00:03.379923
Trend lines re-computed and checked.
12:15:04.215346
Trend lines re-computed and checked.
12:30:03.996420
Trend lines re-computed and checked.
12:45:03.723689
Trend lines re-computed and checked.
13:00:03.539742
Trend lines re-computed and checked.
13:15:03.805581
Trend lines re-computed and checked.
13:30:03.646556
Trend lines re-computed and checked.
13:45:03.467897
Trend lines re-computed and checked.
14:00:03.308164
Trend lines re-computed and checked.
14:15:04.099843
Trend lines re-computed and checked.
14:30:03.909634
Trend lines re-computed and checked.
14:45:04.139852
Trend lines re-computed and checked.
15:00:03.863803
15:15:03.560118
15:30:03.333173
15:45:04.006242
09:00:03.920134
09:15:04.821543
09:30:03.534071
Trend lines re-computed and checked.
09:45:04.278610
Trend lines re-computed and checked.
10:00:03.936695
Trend lines re-computed and checked.
10:15:03.699496
Trend lines re-computed and checked.
10:30:03.444235
Trend lines re-computed and checked.
10:45:04.152643
Trend lines re-computed and checked.
11:00:03.916678
Trend lines re-computed and checked.
11:15:03.731966
Trend lines re-computed and checked.
11:30:03.453038
Trend lines re-computed and checked.
11:45:04.223402
Trend lines re-computed and checked.
12:00:03.952417
Trend lines re-computed and checked.
12:15:03.706357
Trend lines re-computed and checked.
12:30:03.534578
Trend lines re-computed and checked.
12:45:03.318733
Trend lines re-computed and checked.
13:00:04.208968
Trend lines re-computed and checked.
13:15:03.958595
Trend lines re-computed and checked.
13:30:03.639316
Trend lines re-computed and checked.
13:45:03.436670
Trend lines re-computed and checked.
14:00:04.217361
Trend lines re-computed and checked.
14:15:04.010932
Trend lines re-computed and checked.
14:30:03.777136
Trend lines re-computed and checked.
14:45:03.601806
Trend lines re-computed and checked.
15:00:03.395790
15:15:04.208945
15:30:03.936648
15:45:03.677601
09:00:04.753932
09:15:03.526250
09:30:03.261579
Trend lines re-computed and checked.
09:45:04.061258
Trend lines re-computed and checked.
10:00:03.839517
Trend lines re-computed and checked.
10:15:03.622699
Trend lines re-computed and checked.
10:30:03.437444
Trend lines re-computed and checked.
10:45:04.160223
Trend lines re-computed and checked.
11:00:03.882479
Trend lines re-computed and checked.
11:15:03.529374
Trend lines re-computed and checked.
11:30:04.188544
Trend lines re-computed and checked.
11:45:03.978425
Trend lines re-computed and checked.
12:00:03.605178
Trend lines re-computed and checked.
12:15:03.272589
Trend lines re-computed and checked.
12:30:03.940290
Trend lines re-computed and checked.
12:45:03.662318
Trend lines re-computed and checked.
13:00:03.379848
Trend lines re-computed and checked.
13:15:04.094450
Trend lines re-computed and checked.
13:30:03.753797
Trend lines re-computed and checked.
13:45:03.428795
Trend lines re-computed and checked.
14:00:04.119508
Trend lines re-computed and checked.
14:15:03.813918
Trend lines re-computed and checked.
14:30:03.510821
Trend lines re-computed and checked.
14:45:04.267118
Trend lines re-computed and checked.
15:00:03.931414
15:15:03.583450
15:30:03.341896
15:45:03.970122
09:00:04.917247
09:15:03.596807
09:30:03.313107
Trend lines re-computed and checked.
09:45:04.069191
Trend lines re-computed and checked.
10:00:03.771103
Trend lines re-computed and checked.
10:15:03.484238
Trend lines re-computed and checked.
10:30:04.172651
Trend lines re-computed and checked.
10:45:03.805891
Trend lines re-computed and checked.
11:00:03.482094
Trend lines re-computed and checked.
11:15:04.161972
Trend lines re-computed and checked.
11:30:03.827473
Trend lines re-computed and checked.
11:45:03.480038
Trend lines re-computed and checked.
12:00:04.121879
Trend lines re-computed and checked.
12:15:03.768248
Trend lines re-computed and checked.
12:30:03.395267
Trend lines re-computed and checked.
12:45:04.011864
Trend lines re-computed and checked.
13:00:03.685296
Trend lines re-computed and checked.
13:15:03.249873
Trend lines re-computed and checked.
13:30:03.927010
Trend lines re-computed and checked.
13:45:03.553381
Trend lines re-computed and checked.
14:00:04.193408
Trend lines re-computed and checked.
14:15:03.789897
Trend lines re-computed and checked.
14:30:03.435326
Trend lines re-computed and checked.
14:45:04.080986
Trend lines re-computed and checked.
15:00:03.706410
15:15:03.282758
15:30:03.983959
15:45:03.528972
09:00:03.231311
09:15:03.902807
09:30:03.541539
Trend lines re-computed and checked.
09:45:04.193840
Trend lines re-computed and checked.
10:00:03.779482
Trend lines re-computed and checked.
10:15:03.387652
Trend lines re-computed and checked.
10:30:04.070277
Trend lines re-computed and checked.
10:45:03.686474
Trend lines re-computed and checked.
11:00:03.237675
Trend lines re-computed and checked.
11:15:03.880339
Trend lines re-computed and checked.
11:30:03.491697
Trend lines re-computed and checked.
11:45:04.157183
Trend lines re-computed and checked.
12:00:03.791707
Trend lines re-computed and checked.
12:15:03.448276
Trend lines re-computed and checked.
12:30:04.155716
Trend lines re-computed and checked.
12:45:03.821386
Trend lines re-computed and checked.
13:00:03.437247
Trend lines re-computed and checked.
13:15:04.073902
Trend lines re-computed and checked.
13:30:03.727660
Trend lines re-computed and checked.
13:45:03.332438
Trend lines re-computed and checked.
14:00:03.874227
Trend lines re-computed and checked.
14:15:03.608598
Trend lines re-computed and checked.
14:30:04.173175
Trend lines re-computed and checked.
14:45:03.809337
Trend lines re-computed and checked.
15:00:03.545521
15:15:04.872183
15:30:03.470568
15:45:04.182201
09:00:05.291014
09:15:04.124528
09:30:03.749099
Trend lines re-computed and checked.
09:45:03.390870
Trend lines re-computed and checked.
10:00:04.031097
Trend lines re-computed and checked.
10:15:03.673927
Trend lines re-computed and checked.
10:30:03.243179
Trend lines re-computed and checked.
10:45:03.938189
Trend lines re-computed and checked.
11:00:03.550845
Trend lines re-computed and checked.
11:15:04.150748
Trend lines re-computed and checked.
11:30:04.481964
Trend lines re-computed and checked.
11:45:04.126092
Trend lines re-computed and checked.
12:00:03.783383
Trend lines re-computed and checked.
12:15:03.375198
Trend lines re-computed and checked.
12:30:04.128151
Trend lines re-computed and checked.
12:45:03.728606
Trend lines re-computed and checked.
13:00:03.471285
Trend lines re-computed and checked.
13:15:04.033662
Trend lines re-computed and checked.
13:30:03.738799
Trend lines re-computed and checked.
13:45:03.387142
Trend lines re-computed and checked.
14:00:03.970630
Trend lines re-computed and checked.
14:15:03.664504
Trend lines re-computed and checked.
14:30:03.291557
Trend lines re-computed and checked.
14:45:03.878967
Trend lines re-computed and checked.
15:00:03.508481
15:15:04.035972
15:30:03.703535
15:45:03.284744
09:00:05.270723
09:15:03.875397
09:30:03.496800
Trend lines re-computed and checked.
09:45:04.965883
Trend lines re-computed and checked.
10:00:03.652095
Trend lines re-computed and checked.
10:15:03.291611
Trend lines re-computed and checked.
10:30:03.955622
Trend lines re-computed and checked.
10:45:03.548446
Trend lines re-computed and checked.
11:00:04.171770
Trend lines re-computed and checked.
11:15:03.813252
Trend lines re-computed and checked.
11:30:03.527692
Trend lines re-computed and checked.
11:45:04.096696
Trend lines re-computed and checked.
12:00:03.683685
Trend lines re-computed and checked.
12:15:03.352205
Trend lines re-computed and checked.
12:30:03.965673
Trend lines re-computed and checked.
12:45:03.601522
Trend lines re-computed and checked.
13:00:03.258842
Trend lines re-computed and checked.
13:15:03.979811
Trend lines re-computed and checked.
13:30:03.615855
Trend lines re-computed and checked.
13:45:03.191130
Trend lines re-computed and checked.
14:00:03.843732
Trend lines re-computed and checked.
14:15:03.461072
Trend lines re-computed and checked.
14:30:04.099687
Trend lines re-computed and checked.
14:45:03.771738
Trend lines re-computed and checked.
15:00:03.349713
15:15:03.958836
15:30:03.596966
15:45:03.228205
09:00:05.240702
09:15:03.859021
09:30:03.483025
Trend lines re-computed and checked.
09:45:04.205261
Trend lines re-computed and checked.
10:00:03.766758
Trend lines re-computed and checked.
10:15:03.342292
Trend lines re-computed and checked.
10:30:04.033894
Trend lines re-computed and checked.
10:45:03.661670
Trend lines re-computed and checked.
11:00:03.330240
Trend lines re-computed and checked.
11:15:03.910016
Trend lines re-computed and checked.
11:30:03.617592
Trend lines re-computed and checked.
11:45:03.294704
Trend lines re-computed and checked.
12:00:03.841716
Trend lines re-computed and checked.
12:15:03.610919
Trend lines re-computed and checked.
12:30:03.354556
Trend lines re-computed and checked.
12:45:03.933603
Trend lines re-computed and checked.
13:00:03.574147
Trend lines re-computed and checked.
13:15:03.236764
Trend lines re-computed and checked.
13:30:03.898012
Trend lines re-computed and checked.
13:45:03.538229
Trend lines re-computed and checked.
14:00:04.105999
Trend lines re-computed and checked.
14:15:03.710552
Trend lines re-computed and checked.
14:30:03.395737
Trend lines re-computed and checked.
14:45:04.020330
Trend lines re-computed and checked.
15:00:03.654816
15:15:03.436960
15:30:04.549437
15:45:04.340902
09:00:05.190121
09:15:03.968201
09:30:03.715551
{'date': '2025-07-07', 'value': 1712.5} rec
1712.5 line_price
1796.3 1796.3 1796.3
1703.9375 1721.0625
True
[09:30] TrendLine 7 touched at 1712.5 (bar 2025-07-07 09:15:03–2025-07-07 09:30:03)
{'date': '2025-07-07', 'value': 2015.560802469554} rec
2015.560802469554 line_price
1797.0 1796.3 1796.3
2005.483002469554 2025.638602469554
True
[09:30] TrendLine 8 touched at 2015.560802469554 (bar 2025-07-07 09:15:03–2025-07-07 09:30:03)
{'date': '2025-07-07', 'value': 8990.0} rec
8990.0 line_price
9021.5 9009.0 9021.5
8945.0500 9034.9500
True
[09:30] TrendLine 9 touched at 8990.0 (bar 2025-07-07 09:15:03–2025-07-07 09:30:03)
Trend lines re-computed and checked.
09:45:03.323216
Trend lines re-computed and checked.
10:00:03.941855
Trend lines re-computed and checked.
10:15:04.207770
Trend lines re-computed and checked.
10:30:03.902746
{'date': '2025-07-07', 'value': 1473.6} rec
1473.6 line_price
1486.9 1481.5 1483.2
1466.2320 1480.9680
True
[10:30] TrendLine 10 touched at 1473.6 (bar 2025-07-07 10:15:03–2025-07-07 10:30:03)
{'date': '2025-07-07', 'value': 1707.9382636535431} rec
1707.9382636535431 line_price
1486.5 1486.4 1486.5
1699.3985636535431 1716.4779636535431
True
[10:30] TrendLine 11 touched at 1707.9382636535431 (bar 2025-07-07 10:15:03–2025-07-07 10:30:03)
Trend lines re-computed and checked.
10:45:04.295905
Trend lines re-computed and checked.
11:00:03.925384
Trend lines re-computed and checked.
11:15:03.634433
Trend lines re-computed and checked.
11:30:03.331441
Trend lines re-computed and checked.
11:45:03.820930
Trend lines re-computed and checked.
12:00:03.490213
Trend lines re-computed and checked.
12:15:04.170845
Trend lines re-computed and checked.
12:30:03.879612
Trend lines re-computed and checked.
12:45:03.500525
Trend lines re-computed and checked.
13:00:04.215949
Trend lines re-computed and checked.
13:15:03.847945
Trend lines re-computed and checked.
13:30:03.538708
Trend lines re-computed and checked.
13:45:03.594441
Trend lines re-computed and checked.
14:00:03.317200
Trend lines re-computed and checked.
14:15:03.997344
Trend lines re-computed and checked.
14:30:04.534331
Trend lines re-computed and checked.
14:45:04.122563
Trend lines re-computed and checked.
15:00:03.801529
15:15:03.491801
15:30:04.120718
15:45:03.785478
09:00:05.238948
09:15:04.845616
09:30:03.753095
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1483.9 1483.9 1483.9
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1477.6} rec
1477.6 line_price
1483.9 1483.9 1483.9
1403.7200 1551.4800
True
[09:30] TrendLine 1 touched at 1477.6 (bar 2025-07-08 09:15:03–2025-07-08 09:30:03)
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1484.8 1483.9 1483.9
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
09:45:03.767077
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1488.5 1483.5 1487.7
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1488.5 1483.5 1487.7
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
10:00:04.631236
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1487.2 1480.3 1485.1
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1487.2 1480.3 1485.1
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
10:15:03.750266
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1476.9 1476.9 1476.9
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1476.9 1476.9 1476.9
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
10:30:04.706716
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1475.3 1475.0 1475.3
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1475.3 1475.0 1475.3
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
10:45:03.856400
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1468.1 1468.0 1468.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1468.1 1468.0 1468.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
11:00:03.820366
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1473.9 1473.9 1473.9
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1473.9 1473.9 1473.9
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
11:15:04.040366
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1476.0 1469.0 1474.5
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1476.0 1469.0 1474.5
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
11:30:04.677300
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1467.2 1467.0 1467.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1467.2 1467.0 1467.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
11:45:04.133591
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1470.0 1470.0 1470.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1470.0 1470.0 1470.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
12:00:04.186979
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1472.3 1472.0 1472.3
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1472.3 1472.0 1472.3
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
12:15:05.281016
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1475.0 1474.1 1475.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1475.0 1474.1 1475.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
12:30:04.690066
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1478.8 1478.1 1478.1
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1478.8 1478.1 1478.1
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
12:45:03.792948
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1482.0 1482.0 1482.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1482.0 1482.0 1482.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
13:00:04.071487
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1483.0 1483.0 1483.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1483.0 1483.0 1483.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
13:15:04.444989
{'date': '2025-07-08', 'value': 1716.0494612615} rec
1716.0494612615 line_price
1483.0 1483.0 1483.0
1630.2469612615 1801.8519612615
False
{'date': '2025-07-08', 'value': 1360.0097388392624} rec
1360.0097388392624 line_price
1483.0 1483.0 1483.0
1292.0092388392624 1428.0102388392624
False
Trend lines re-computed and checked.
13:30:03.951029
Trend lines re-computed and checked.
13:45:04.471864
Trend lines re-computed and checked.
14:00:05.035314
Trend lines re-computed and checked.
14:15:03.986596
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:30:03.842414
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:45:03.752499
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
15:00:03.824819
15:15:04.576842
15:30:04.105817
15:45:04.283763
09:00:05.685434
09:15:04.370548
09:30:05.052265
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
09:45:05.082287
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
10:00:05.004643
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
10:15:04.933689
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
10:30:04.706311
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
10:45:04.592472
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
11:00:04.351655
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
11:15:05.205351
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
11:30:05.352256
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
11:45:05.380370
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
12:00:05.417753
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
12:15:04.788665
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
12:30:04.443788
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
12:45:04.427900
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
13:00:05.362897
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
13:15:04.979685
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
13:30:04.466127
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
13:45:05.081335
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:00:04.139120
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:15:04.531192
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:30:03.558477
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
14:45:04.060062
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 46, in run
    core_tl = CoreTrendLine(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 197, in __init__
    self.slope = math.tan(math.radians(angle_deg)) * price_to_bar_ratio
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
15:00:04.424527
15:15:04.530894
15:30:03.488681
15:45:04.501422
09:00:04.955803
09:15:04.572745
09:30:04.421425
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
115.69 115.69 115.69
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3437.0} rec
3437.0 line_price
3431.5 3430.0 3431.5
3265.1500 3608.8500
True
[09:30] TrendLine 25 touched at 3437.0 (bar 2025-07-10 09:15:04–2025-07-10 09:30:04)
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3431.5 3430.0 3431.5
3765.071593818483 4161.394993818483
False
{'date': '2025-07-10', 'value': 3177.4904581280275} rec
3177.4904581280275 line_price
3431.5 3430.0 3431.5
3018.6159581280275 3336.3649581280275
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
09:45:04.597700
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
115.27 115.2 115.27
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3425.7 3425.2 3425.4
3765.071593818483 4161.394993818483
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
10:00:03.784127
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
114.98 114.98 114.98
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3434.3 3434.0 3434.0
3765.071593818483 4161.394993818483
False
{'date': '2025-07-10', 'value': 3177.4904581280275} rec
3177.4904581280275 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:15:04.092813
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
114.83 114.83 114.83
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3433.2 3432.7 3432.7
3765.071593818483 4161.394993818483
False
{'date': '2025-07-10', 'value': 3177.4904581280275} rec
3177.4904581280275 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:30:04.281071
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
114.85 114.85 114.85
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3437.6 3437.6 3437.6
3765.071593818483 4161.394993818483
False
{'date': '2025-07-10', 'value': 3177.4904581280275} rec
3177.4904581280275 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:45:05.090400
{'date': '2025-07-10', 'value': 159.0092739865313} rec
159.0092739865313 line_price
114.6 114.6 114.6
151.0587739865313 166.9597739865313
False
{'date': '2025-07-10', 'value': 3963.233293818483} rec
3963.233293818483 line_price
3433.8 3433.8 3433.8
3765.071593818483 4161.394993818483
False
{'date': '2025-07-10', 'value': 3177.4904581280275} rec
3177.4904581280275 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:00:04.252788
{'date': '2025-07-10', 'value': 175.66} rec
175.66 line_price
178.69 178.69 178.69
166.8770 184.4430
True
[11:00] TrendLine 10 touched at 175.66 (bar 2025-07-10 10:45:04–2025-07-10 11:00:04)
{'date': '2025-07-10', 'value': 1539.1166469092416} rec
1539.1166469092416 line_price
1254.0 1254.0 1254.0
1462.1608469092416 1616.0724469092416
False
{'date': '2025-07-10', 'value': 1146.2452290640138} rec
1146.2452290640138 line_price
1254.0 1254.0 1254.0
1088.9329290640138 1203.5575290640138
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:15:04.004397
{'date': '2025-07-10', 'value': 1539.1166469092416} rec
1539.1166469092416 line_price
1257.4 1257.4 1257.4
1462.1608469092416 1616.0724469092416
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.56 178.14 178.5
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
11:30:04.156317
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.2 178.2 178.2
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.2 178.2 178.2
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
11:45:04.831388
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.0 177.97 178.0
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.0 177.97 178.0
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
12:00:04.582222
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.16 178.01 178.16
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.16 178.01 178.16
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
12:15:04.461555
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.49 178.42 178.42
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.49 178.42 178.42
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
12:30:04.940786
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.7 178.7 178.7
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.7 178.7 178.7
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
12:45:04.678606
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.41 178.34 178.4
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.41 178.34 178.4
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
13:00:04.279321
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.18 178.17 178.18
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.18 178.17 178.18
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
13:15:05.182318
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
177.7 177.62 177.7
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
177.7 177.6 177.7
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
13:30:04.954666
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
177.99 177.89 177.89
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
177.99 177.89 177.89
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
13:45:04.589403
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
177.5 177.5 177.5
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
177.5 177.5 177.5
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
14:00:04.697344
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
177.87 177.82 177.87
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
177.87 177.82 177.87
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
14:15:04.714133
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.12 178.1 178.1
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.12 178.1 178.1
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
14:30:04.509327
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.41 178.41 178.41
144.00520773648695 159.16360773648695
False
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.41 178.41 178.41
213.25647159448817 235.70447159448817
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
14:45:04.478032
{'date': '2025-07-10', 'value': 224.48047159448817} rec
224.48047159448817 line_price
178.7 178.7 178.7
213.25647159448817 235.70447159448817
False
{'date': '2025-07-10', 'value': 151.58440773648695} rec
151.58440773648695 line_price
178.7 178.64 178.7
144.00520773648695 159.16360773648695
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
15:00:04.513340
15:15:04.039509
15:30:04.137255
15:45:04.608186
09:00:05.101741
09:15:04.581163
09:30:03.550573
{'date': '2025-07-11', 'value': 151.8309804495026} rec
151.8309804495026 line_price
178.93 178.93 178.93
144.2394804495026 159.4224804495026
False
{'date': '2025-07-11', 'value': 225.49437129548278} rec
225.49437129548278 line_price
178.93 178.93 178.93
214.21967129548278 236.76907129548278
False
{'date': '2025-07-11', 'value': 1280.0} rec
1280.0 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
09:45:04.122281
{'date': '2025-07-11', 'value': 225.49437129548278} rec
225.49437129548278 line_price
178.12 178.04 178.04
214.21967129548278 236.76907129548278
False
{'date': '2025-07-11', 'value': 151.8309804495026} rec
151.8309804495026 line_price
178.12 178.04 178.04
144.2394804495026 159.4224804495026
False
{'date': '2025-07-11', 'value': 1280.0} rec
1280.0 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:00:04.284745
{'date': '2025-07-11', 'value': 151.8309804495026} rec
151.8309804495026 line_price
177.45 177.45 177.45
144.2394804495026 159.4224804495026
False
{'date': '2025-07-11', 'value': 1280.0} rec
1280.0 line_price
1270.3 1265.3 1266.0
1216.0000 1344.0000
True
[10:00] TrendLine 7 touched at 1280.0 (bar 2025-07-11 09:45:04–2025-07-11 10:00:04)
{'date': '2025-07-11', 'value': 1351.15} rec
1351.15 line_price
1413.9 1409.1 1409.3
1283.5925 1418.7075
True
[10:00] TrendLine 16 touched at 1351.15 (bar 2025-07-11 09:45:04–2025-07-11 10:00:04)
{'date': '2025-07-11', 'value': 1675.934611028595} rec
1675.934611028595 line_price
1410.0 1410.0 1410.0
1592.137911028595 1759.731311028595
False
{'date': '2025-07-11', 'value': 1190.9839546258922} rec
1190.9839546258922 line_price
1410.0 1410.0 1410.0
1131.4347546258922 1250.5331546258922
False
{'date': '2025-07-11', 'value': 114.79999999999998} rec
114.79999999999998 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:15:03.980380
{'date': '2025-07-11', 'value': 92.49839874537739} rec
92.49839874537739 line_price
112.89 112.86 112.89
87.87349874537739 97.12329874537739
False
{'date': '2025-07-11', 'value': 3240.0} rec
3240.0 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
10:30:04.845891
{'date': '2025-07-11', 'value': 4308.911378068794} rec
4308.911378068794 line_price
3155.5 3152.3 3154.4
4093.465778068794 4524.356978068794
False
{'date': '2025-07-11', 'value': 1675.934611028595} rec
1675.934611028595 line_price
1418.4 1418.2 1418.4
1592.137911028595 1759.731311028595
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
10:45:04.247672
{'date': '2025-07-11', 'value': 114.79999999999998} rec
114.79999999999998 line_price
112.58 112.57 112.58
109.05999999999998 120.53999999999998
True
[10:45] TrendLine 19 touched at 114.79999999999998 (bar 2025-07-11 10:30:04–2025-07-11 10:45:04)
{'date': '2025-07-11', 'value': 3240.0} rec
3240.0 line_price
3169.4 3167.8 3169.0
3078.0000 3402.0000
True
[10:45] TrendLine 22 touched at 3240.0 (bar 2025-07-11 10:30:04–2025-07-11 10:45:04)
{'date': '2025-07-11', 'value': 4308.911378068794} rec
4308.911378068794 line_price
3169.4 3166.0 3169.0
4093.465778068794 4524.356978068794
False
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3169.4 3166.0 3169.0
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 8.317799401989225} rec
8.317799401989225 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:00:04.450367
{'date': '2025-07-11', 'value': 4308.911378068794} rec
4308.911378068794 line_price
3181.5 3180.5 3181.5
4093.465778068794 4524.356978068794
False
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:15:04.195372
{'date': '2025-07-11', 'value': 2256.6130726600345} rec
2256.6130726600345 line_price
2696.3 2696.0 2696.0
2143.7823726600345 2369.4437726600345
False
{'date': '2025-07-11', 'value': 8.317799401989225} rec
8.317799401989225 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:30:04.967801
{'date': '2025-07-11', 'value': 8.317799401989225} rec
8.317799401989225 line_price
7.16 7.15 7.16
7.901899401989225 8.733699401989225
False
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
11:45:04.573794
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3188.0 3187.5 3187.5
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 2256.6130726600345} rec
2256.6130726600345 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
12:00:03.802078
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3178.5 3177.5 3177.5
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 6.783145426031304} rec
6.783145426031304 line_price
7.21 7.2 7.21
6.443945426031304 7.122345426031304
False
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 42, in run
    full_df = self.client.get_full_history(tl.security_id)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 41, in get_full_history
    return self.get_ticker_data(security_id, early)
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 76, in get_ticker_data
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/historical
12:15:04.063512
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3179.3 3178.0 3179.0
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 7.29} rec
7.29 line_price
7.22 7.22 7.22
6.9255 7.6545
True
[12:15] TrendLine 28 touched at 7.29 (bar 2025-07-11 12:00:04–2025-07-11 12:15:04)
{'date': '2025-07-11', 'value': 237.5} rec
237.5 line_price
242.2 242.14 242.2
225.6250 249.3750
True
[12:15] TrendLine 31 touched at 237.5 (bar 2025-07-11 12:00:04–2025-07-11 12:15:04)
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
242.2 242.14 242.2
257.35828056464984 284.44868056464984
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
242.2 242.14 242.2
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 3238.791617273104} rec
3238.791617273104 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
12:30:04.498968
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3173.3 3172.8 3173.3
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
12:45:04.042370
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3188.2 3188.1 3188.1
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
242.3 242.29 242.3
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 3238.791617273104} rec
3238.791617273104 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
13:00:04.124638
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3206.7 3186.9 3190.0
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
242.26 242.25 242.25
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
13:15:04.221770
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3193.5 3193.5 3193.5
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
242.0 242.0 242.0
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
13:30:04.601897
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3200.0 3193.5 3194.0
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
242.19 242.04 242.04
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
13:45:03.978119
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3188.9 3188.9 3188.9
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
241.62 241.61 241.61
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
14:00:05.025161
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3193.2 3193.2 3193.2
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
241.87 241.81 241.87
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
14:15:04.581240
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3191.1 3191.1 3191.1
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
241.75 241.67 241.67
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
14:30:03.938882
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3185.7 3185.2 3185.7
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
241.4 241.34 241.39
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
14:45:04.434288
{'date': '2025-07-11', 'value': 2712.8712430725564} rec
2712.8712430725564 line_price
3184.8 3184.8 3184.8
2577.2276430725564 2848.5148430725564
False
{'date': '2025-07-11', 'value': 221.0272263460174} rec
221.0272263460174 line_price
241.42 241.33 241.33
209.9758263460174 232.0786263460174
False
{'date': '2025-07-11', 'value': 270.90348056464984} rec
270.90348056464984 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 141, in handle
    checker.run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
15:00:03.620880
15:15:03.449340
15:30:04.234781
15:45:04.189740
False
Outside market hours; skipping crossover check.
False
Outside market hours; skipping crossover check.
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3126.0 3124.5 3124.9
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
243.52 243.45 243.45
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3106.0 3106.0 3106.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.23 242.18 242.18
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3118.3 3117.0 3118.3
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.42 242.37 242.37
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3127.7 3126.2 3126.6
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.44 242.38 242.44
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3139.5 3138.5 3138.5
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.67 242.65 242.67
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3130.5 3130.2 3130.2
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.7 242.69 242.69
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3139.4 3130.0 3133.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.85 242.84 242.85
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3129.4 3129.0 3129.4
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.55 242.55 242.55
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3130.3 3130.0 3130.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.5 242.36 242.36
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3117.5 3115.1 3117.5
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.63 242.54 242.59
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3115.6 3115.6 3115.6
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.84 242.83 242.83
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3117.8 3117.1 3117.8
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
243.59 243.49 243.49
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3120.7 3120.7 3120.7
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
243.27 243.26 243.26
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3131.9 3115.6 3119.7
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.98 242.93 242.95
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3129.0 3129.0 3129.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
242.46 242.32 242.32
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3126.0 3126.0 3126.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
243.09 243.04 243.09
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
False
{'date': '2025-07-14', 'value': 2720.7615698890572} rec
2720.7615698890572 line_price
3126.0 3126.0 3126.0
2584.7234698890572 2856.7996698890572
False
{'date': '2025-07-14', 'value': 221.27379905903302} rec
221.27379905903302 line_price
244.12 244.06 244.12
210.21009905903302 232.33749905903302
False
{'date': '2025-07-14', 'value': 271.9173802656444} rec
271.9173802656444 line_price
Traceback (most recent call last):
  File "/home/ubuntu/Geo-Algo/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/Geo-Algo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 138, in handle
    TrendLineChecker(settings.DATA_DHAN_ACCESS_TOKEN).run()
  File "/home/ubuntu/Geo-Algo/market/management/commands/check_trend_lines.py", line 79, in run
    intraday = self.client.get_intraday_ohlc(
  File "/home/ubuntu/Geo-Algo/market/dhan.py", line 116, in get_intraday_ohlc
    resp.raise_for_status()
  File "/home/ubuntu/Geo-Algo/venv/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.dhan.co/v2/charts/intraday
